### ISSUE TITLE
Add details in the list

### ISSUE THREAD

**Issue by benzen** [h3xstream/montreal_isp#2]
It would be nice to add some possibility.

I can think of telephone, tv plan.

It would also be nice to state in a separate column if the plan is for cable or dsl, with possibilty to do filtering on this field

**Comment by h3xstream** [comment]
Telephone and TV are not the objective of this project.
But, the Cable/DSL indicator is something I am interested to add.

**Comment by millette** [comment]
Hi,

I was glad to find your project, mostly up to date. I can take a stab at this (internet service type).

**Comment by h3xstream** [comment]
@millette Don't hesitate to add the field and/or add the filter.
